### ISSUE TITLE
Incoming MQTT

### ISSUE THREAD

**Issue by damienemmerson** [toddaustin07/MQTT_SmartApp#2]
Thanks for your contribution @toddaustin07. This is exactly what i need in my environment!
I was wondering if you would be able to expand on the smartapp so that it can accept incoming MQTT messages so that the state of devices in smartthings can be updated.

**Comment by toddaustin07** [comment]
Hi there and you are most welcome!

I will consider your request.  It's a fair amount of work to accomplish that so maybe sometime in the future.  In the meantime, if you have a specific need for a SmartThings device to be updated via MQTT, take a look at my MQTT Discovery/Handler driver, which can do just that if you have control over the topic.  Otherwise, I also have some more specific device type drivers that might be useful - just let me know.
